### PR TITLE
Add content on About Page

### PR DESCRIPTION
**Pull request by syauqy**
This is solving this #16 issue on adding content on About Page. Kindly check @Sarthak-Mittal

### CODE REVIEW

**Review by Sarthak-Mittal — CHANGES_REQUESTED** [review]
The content looks great but overall it doesn't align with the general layout and design of the application. Try making a separate .container class outside .jumbotron and putting all the content there. 

Make sure you only make PR for only one issue i.e. #16 . Remove changes for #18 

IMPORTANT:: Do not make PR with changed package-lock.json, package.json and tsconfig.json

**Comment by syauqy** [comment]
Okay, I'll change it.
Thank you for the review

**Comment by syauqy** [comment]
Sorry, quick question.
Did you mean all the content is the heading of "About this project" to the rest of the content?
So I leave the display-4 About title inside the jumbotron?

**Comment by syauqy** [comment]
How about this? @Sarthak-Mittal 
About

**Comment by Sarthak-Mittal** [comment]
Wow! This looks awesome.

**Comment by syauqy** [comment]
Ok, I'll push it to PR then

**Comment by syauqy** [comment]
pushed new commit @Sarthak-Mittal . please check it

**Comment by Sarthak-Mittal** [comment]
> The content looks great but overall it doesn't align with the general layout and design of the application. Try making a separate .container class outside .jumbotron and putting all the content there.
> 
> Make sure you only make PR for only one issue i.e. #16 . Remove changes for #18
> 
> IMPORTANT:: Do not make PR with changed package-lock.json, package.json and tsconfig.json

You need to address the last two lines also. 
Good things is, About page is good to merge now but those two need to be addressed before the merge.

**Comment by syauqy** [comment]
Sorry, any advice to do it @Sarthak-Mittal ? Do I need to create a new PR?

**Comment by Sarthak-Mittal** [comment]
No need to make a new PR. A quick hack could be, you can copy those from my repo to your own local code. Make a commit for that and then I will merge. Later you can change them back to your own original files.

**Comment by syauqy** [comment]
Hi @Sarthak-Mittal do you still need a new commit from me?

**Comment by Sarthak-Mittal** [comment]
No, I have resolved those already and merged.

**Pull request merged**
