### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by bishtsaurabh5**
This commit adds the dockerfile
to containerize the project

1)Run docker build . -t "image_name"
2)Run docker run --net=host <image_name>
to run the docker image

### CODE REVIEW

**Comment by Sarthak-Mittal** [comment]
Good work! Could you also document the steps to set-up and getting started with Docker in the Readme file?

**Comment by bishtsaurabh5** [comment]
Sure I will add the steps in the Readme File

**Comment by bishtsaurabh5** [comment]
Done changes made and Updated Readme file

**Comment by Sarthak-Mittal** [comment]
Good work @bishtsaurabh5 !

**Pull request merged**
