### PR TITLE
Footer added and animation changed

### PR DESCRIPTION
**Pull request by rohanshenoy96**
Created a responsive footer. Created a new angular animation which is similar to the expected one without the router navigation issue. #28 
image

Feel free to change text in footer

### CODE REVIEW

**Comment by rohanshenoy96** [comment]
@Sarthak-Mittal Cool I'll fix the back to top button. Can u please elaborate on what fixed footer is?

**Comment by Sarthak-Mittal** [comment]
Sorry for using incorrect terminologies, my bad. I'll reframe everything. What we need is a footer (sticky) that "sticks" to the bottom of the browser window. But not always, if there is enough content on the page to push the footer lower, it does that. But if the content on the page is short, a sticky footer will still hang to the bottom of the browser window.

[This might come in handy](https://css-tricks.com/couple-takes-sticky-footer/)

**Comment by rohanshenoy96** [comment]
Cool I will make changes accordingly and check in. Thanks for the explanation.

**Comment by rohanshenoy96** [comment]
Hi @Sarthak-Mittal. Added footer as per the requirement and added smooth scroll feature to back to top button. Let me know if you need anything else.

**Comment by Sarthak-Mittal** [comment]
Looks great buddy, Thanks!

**Pull request merged**
