### PR TITLE
reworked search & clear button Fixes Sarthak-Mittal/ifsc#4

### PR DESCRIPTION
**Pull request by smatthies**
changed the input type to search, so that the input field includes the clear button:
 - therefore could get rid of the clear() function
 - using semantic html here is better practice for accessibilty and the clear button is only visible when really needed

changed the search button to the blue used before to give it more of a call-to-action aesthetic
- reworked the disabled state to fit into the the design of the input field

### CODE REVIEW

**Review by Sarthak-Mittal — CHANGES_REQUESTED** [review]
This looks great, I think it misses out on only one thing. The `clear()` function was also used to return back to the original state as it was when the user landed on the app. The variable `toogleDisplay` is used to maintain that, it would be great if you could keep that feature intact.

Otherwise, everything else seems perfect!

**Comment by smatthies** [comment]
> This looks great, I think it misses out on only one thing. The `clear()` function was also used to return back to the original state as it was when the user landed on the app. The variable `toogleDisplay` is used to maintain that, it would be great if you could keep that feature intact.
> 
> Otherwise, everything else seems perfect!

**Comment by smatthies** [comment]
Could you tell me where the toggleDisplay is used? I've looked into it and the variable is set in app.components.ts in line 27 and 12 - but I couln't find a place where it is used. 

Which state would change and what is the expected behaviour? If I use the clear button atm the input is cleared and the search button will disabled again.

**Comment by Sarthak-Mittal** [comment]
> Could you tell me where the toggleDisplay is used? I've looked into it and the variable is set in app.components.ts in line 27 and 12 - but I couln't find a place where it is used.
> 
> Which state would change and what is the expected behaviour? If I use the clear button atm the input is cleared and the search button will disabled again.

In app.component.html Line 12,13 and 38. It is used to hide/show toggle sub-headings and display area. The expected behaviour is to hide API data and clear input field when clear button is clicked.

**Comment by smatthies** [comment]
Please review again - instead of implementing the toggleDisplay I rewrote it so that the search button and this use the same functionality. 
Although I would consider to not do hide the headline like this and would add the text as placeholder in the search bar, as it could be disturbing for some people especially with disabilities.

**Comment by Sarthak-Mittal** [comment]
Thanks @smatthies for your contributions. It was of great help. 👍

**Pull request merged**
